const { chromium } = require('playwright');
const express = require('express');
const fs = require('node:fs/promises');
const path = require('node:path');
const assert = require('node:assert/strict');
const output = path.join(__dirname, '../test-results/download');
let browser, server;
const artifact = path.join(output, 'fixture.exe');
(async () => {
  await fs.mkdir(output, { recursive: true });
  const bytes = Buffer.from('MZ-download-fixture-not-an-executable');
  await fs.writeFile(artifact, bytes);
  const app = express();
  require('../desktop-download')(app, artifact);
  app.use(express.static(path.join(__dirname, '../public')));
  server = app.listen(0, '127.0.0.1');
  await new Promise(resolve => server.once('listening', resolve));
  const origin = `http://127.0.0.1:${server.address().port}`;
  browser = await chromium.launch({ headless: true });
  const page = await browser.newPage({ viewport: { width: 1440, height: 940 } });
  await page.goto(origin);
  await page.waitForFunction(() => document.getElementById('desktopBuild').textContent.includes('build de'));
  const downloading = page.waitForEvent('download');
  await page.locator('#desktopDownload').click();
  const download = await downloading;
  assert.equal(download.suggestedFilename(), 'SalaCompartilhada.exe');
  assert.deepEqual(await fs.readFile(await download.path()), bytes);
  await page.locator('.desktop-download').screenshot({ path: path.join(output, 'desktop.png') });
  await page.setViewportSize({ width: 390, height: 844 });
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  await page.locator('.desktop-download').screenshot({ path: path.join(output, 'mobile.png') });
  await fs.unlink(artifact);
  await page.reload();
  await page.waitForFunction(() => document.getElementById('desktopDownload').getAttribute('aria-disabled') === 'true');
  assert.equal(await page.locator('#desktopDownload').getAttribute('href'), null);
  console.log('PASS: homepage downloads exact portable bytes, displays build details, fits mobile and handles missing build');
})().catch(error => { console.error(error); process.exitCode = 1; }).finally(async () => {
  await browser?.close();
  if (server) await new Promise(resolve => server.close(resolve));
  await fs.unlink(artifact).catch(() => {});
});
